language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

install:
  - composer self-update
  - composer install -o

after_deploy:
  - phpunit

addons:
  sonarcloud:
    organization: "c15k0-github"
    token:
      secure: 3812034bb658a5def0f47e792b94eec08388638e

